### ISSUE TITLE
Specifikáció, rendszerterv megírása

### ISSUE THREAD

**Issue by 119simulation** [csonti4000/JumperGame#13]
El kell készíteni a specifikációt és rendszertervet!

**Comment by 119simulation** [comment]
Specifikáció teljesen elkészült, a projektben megtalálható!

**Comment by csonti4000** [comment]
szép munka íg tovább

**Comment by 119simulation** [comment]
Rendszerterv teljesen elkészült, tartalmaz minden információt a szoftver lefejlesztéséhez!
