### ISSUE TITLE
Menü redszer

### ISSUE THREAD

**Issue by csonti4000** [csonti4000/JumperGame#3]
Specifikáció alapján menüredszer elkészítése, új ötletek bele építése!

**Comment by 119simulation** [comment]
Jelenleg kész a főmenü, options átalakítás alatt, Marci mondta a karakter választást ne az optionsbe tegyük, hanem a játék indításakor lehessen kiválasztani. Pause menü megoldására, ha van valakinek ötlete, az írhatja nyugodtan meg scoreboard is 😄

**Comment by 119simulation** [comment]
Mennyi van kész? Mit kell feltennem?

**Comment by csonti4000** [comment]
minden kész van és jó ötlet
