### ISSUE TITLE
skybox

### ISSUE THREAD

**Issue by csonti4000** [csonti4000/JumperGame#4]
játékhoz illő skyboxot feltölteni

**Comment by 119simulation** [comment]
[SkyBox_Blue.zip](https://github.com/csonti4000/JumperGame/files/551060/SkyBox_Blue.zip)
Itt egy skybox ami szerintem megfelőle lenne a játékhoz

**Comment by 119simulation** [comment]
Skybox a játékba implementálva, játék legfrisebb verziója feltöltve!
